use_frameworks!

platform :ios, '13.0'

target 'SpeakerEmbeddingForiOS_Example' do
  pod 'SpeakerEmbeddingForiOS', :path => '../'

  target 'SpeakerEmbeddingForiOS_Tests' do
    inherit! :search_paths

    
  end
end
